version: "2.4"

services:

  db:
    image: postgres:18-alpine
    container_name: routehub-db
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-routehub_user}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-routehub_pass}"
      POSTGRES_DB: "${POSTGRES_DB:-routehub_db}"
    volumes:
      - db_data:/var/lib/postgresql

  api:
    image: routehub/api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: routehub-api
    restart: always
    depends_on:
      - db
    env_file:
      - ./docker-compose.env
    environment:
      RDBMS_URL: "${RDBMS_URL:-postgresql://routehub_user:routehub_pass@db/routehub_db}"
    ports:
      - "8000:80"

volumes:

  db_data:
